{% set data= load_setup_py_data() %}
package:
  name: ts-simactuators
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - TS_CONFIG_ATTCS_DIR
    - LSST_DDS_DOMAIN

test:
  requires:
    - ts-conda-build =0.3
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-utils
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-utils
